### ISSUE TITLE
Request: ToonSync documentation

### ISSUE THREAD

**Issue by scaryghosty** [ToontownRewritten/api-doc#19]
Independent website ToonHQ utilizes "ToonSync" but there is no info on how to integrate with ToonSync that I can find. Does this documentation exist?

**Comment by Lappy** [comment]
At present ToonSync isn't publicly available due to the level of access it provides to the game backend; the OAuth2 segment of it has the potential to be available one day but currently is only available to members of the [partner program](http://toon.town/partners) with a justifiable need for access.

**Comment by scaryghosty** [comment]
Thank you for the insight!
